FROM docker.elastic.co/elasticsearch/elasticsearch:7.2.0
# RUN elasticsearch-plugin remove analysis-kuromoji
# RUN elasticsearch-plugin remove analysis-icu

# copy the configuration file into the container
COPY elasticsearch.yml /usr/share/elasticsearch/config


#RUN elasticsearch-plugin install analysis-kuromoji
#RUN elasticsearch-plugin install analysis-icu
